name: CI

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on:
      - ubuntu-latest
      - linux_amd64
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - run: make test
